### ISSUE TITLE
fork from lmu osc repository and update screenshots

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/collaborative_github_exercise#248]
in this page: https://github.com/lmu-osc/Collaborative-RStudio-GitHub/blob/0ab56c6ab5bbc7e6009327c0a7d3b95dc272748f/fork.md?plain=1#L1

the link and screen shots are wrong

**Comment by MalikaIhle** [comment]
screenshots also need updating here: https://github.com/lmu-osc/Collaborative-RStudio-GitHub/blob/0ab56c6ab5bbc7e6009327c0a7d3b95dc272748f/pull-request.md?plain=1#L1

**Comment by MalikaIhle** [comment]
also for the pull upstream: https://github.com/lmu-osc/Collaborative-RStudio-GitHub/blob/0ab56c6ab5bbc7e6009327c0a7d3b95dc272748f/pull-upstream.md?plain=1#L16

**Comment by MalikaIhle** [comment]
see project description: https://github.com/orgs/lmu-osc/projects/1?pane=issue&itemId=58665266
@MWiehr is that something you could do? update the links, / code / screenshots so it no longers direct to MalikaIhle but to lmu-osc github?

**Comment by MWiehr** [comment]
After having a meeting with Pat I did all the canges localy in a new branch. I ran into a problem when tring to push the changes. I got the following error message:
remote: Permission to lmu-osc/Collaborative-RStudio-GitHub.git denied to MWiehr.
fatal: unable to access 'https://github.com/lmu-osc/Collaborative-RStudio-GitHub.git/': The requested URL returned error: 403

I first tried using the Terminal and (after using a command to merge the branch I created with main locally) I ran into the same problem trying to push the main branch via the R interface. 

I then looked at stackoverflow (https://stackoverflow.com/questions/47465644/github-remote-permission-denied). However after testing push on another project and  not running into the same problem I belive it might be due to a lack of permission rights for lmu-osc???

I´m happy for your insights

**Comment by NeuroShepherd** [comment]
@MWiehr I invited/added you as a collaborator with Write permissions. You should be able to push to the repo now. I would still recommend pushing a new branch if possible just to practice the workflow we discussed.

Given that you're already a Member of the OSC Organization, however, I'm not sure why you weren't able to push to the repo...

**Comment by NeuroShepherd** [comment]
> I first tried using the Terminal and (after using a command to merge the branch I created with main locally) I ran into the same problem trying to push the main branch via the R interface.

FYI I typically add branch protection rules on GitHub that will prevent users from pushing directly to `main`. (But I have not added such a rule to this repo yet.)

**Comment by MWiehr** [comment]
Thank you! It worked now. I will stick to the discussed workflow the next time as I had locally already merged the branches yesterday and didn´t want to redo the exchanges from MalikaIlhe to lmu-osc
